version: 2
updates:
  # Python 패키지 업데이트
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "sj31134"
    assignees:
      - "sj31134"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # 메이저 버전 업데이트는 수동으로 처리
      - dependency-name: "langchain*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "neo4j"
        update-types: ["version-update:semver-major"]
      - dependency-name: "streamlit"
        update-types: ["version-update:semver-major"]

  # GitHub Actions 업데이트
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    reviewers:
      - "sj31134"
    assignees:
      - "sj31134"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions" 